#!/usr/bin/env bash
#
# check-workflows-are-valid.sh
#
# HORO-1472: nothing in this repository validated its own workflow files, so the
# only thing that reported a mistake in one was GitHub, at the moment it tried to
# run it — as a red run with zero jobs and a zero-second duration, which is what
# a parse-time rejection looks like. That failure mode is worse than a normal
# one: there is no job log to read, the error is reported against the pull
# request that merely happened to trigger the workflow, and a workflow that is
# rejected at parse time has not run, so every check it contains is silently
# absent rather than failing.
#
# The class is broader than YAML syntax. `${{ }}` expressions are evaluated in
# places people do not expect (including `inputs.*.description`), a typo in a
# context name is not an error at write time, `uses:` inputs are unvalidated
# against the action's own declaration, and a misindented key becomes a
# different key rather than an error. None of that is caught by a reviewer
# reading the diff.
#
# WHAT IS CHECKED
# ---------------
# actionlint over every workflow in `.github/workflows`, at the version pinned
# in `.github/.actionlint-version`. Findings of any severity are failures: this
# guard has no severity threshold, because a threshold is a decision about which
# findings to stop reading.
#
# The shellcheck integration is REQUIRED to be present and at the pinned
# version, and that is load-bearing rather than tidiness. actionlint hands every
# `run:` block to shellcheck, and when that binary is not on PATH it does not
# warn, error or say anything — it exits 0 having checked no shell at all. A
# comment line in this file must not begin with the tool's own name,
# incidentally: a `# shellcheck ...` line is read as a directive addressed to it,
# and an English sentence is not a valid one. (Measured on this repository: with
# that binary removed from PATH, actionlint reported 0 findings across all four
# workflows where it otherwise reports 6.) A guard that
# quietly halves its own coverage depending on the machine it runs on is the
# thing this file exists to prevent, so absence is a hard failure.
#
# THE ONE NARROWING, AND WHAT IT COSTS
# ------------------------------------
# `.github/workflows/release.yml` is generated by cargo-dist and carries its
# generator's marker. For that file only, findings whose text is "shellcheck
# reported issue ..." are ignored. Everything else actionlint reports about it —
# every parse error, every unknown context, every bad `uses:` input, which is to
# say the entire zero-job-startup-failure class — still fails the guard.
#
# Why: all six of its shellcheck findings are info/style severity, and one of
# them is load-bearing as written. Line 275 passes `$PRERELEASE_FLAG` unquoted
# to `gh release create` specifically so it word-splits to nothing when empty;
# quoting it would pass an empty argument instead. Since `dist init` rewrites
# the file wholesale, "fixing" any of this would be reverted by the next
# regeneration, so enforcing it would make the guard permanently red for reasons
# no one in this repository can act on.
#
# What that costs, stated rather than left implied: a future cargo-dist
# regeneration could introduce a REAL shell quoting bug in release.yml and this
# guard would not catch it. The residual protection is that the file is
# generated rather than hand-edited, so such a bug arrives in a reviewable
# regeneration diff — which is weaker than a mechanical check, and is the reason
# the narrowing is scoped to one named file rather than expressed as a severity
# threshold that would apply everywhere.
#
# The exclusion cannot be borrowed. The generated set is an explicit list here,
# and every file on it must still carry its generator's marker — so if
# cargo-dist stops producing that file, or someone starts hand-editing it, the
# exclusion stops being justified and the guard fails. Conversely a file not on
# the list is linted in full even if it carries a marker, so the marker cannot
# be pasted into a hand-written workflow as an opt-out.
#
# Exit 0 = every workflow is valid. Exit 1 = a finding, or a precondition that
# would have made this guard pass by checking nothing.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

WORKFLOW_DIR=".github/workflows"
VERSION_FILE=".github/.actionlint-version"

# Generated workflows, and the marker that proves each one still is generated.
GENERATED_WORKFLOWS=(
  "${WORKFLOW_DIR}/release.yml"
)
GENERATED_MARKER="autogenerated by dist"

# Applied to the generated set only. Matches actionlint's own wording for a
# finding it obtained from shellcheck, and nothing else.
SHELLCHECK_FINDING="shellcheck reported issue"

for required in "$WORKFLOW_DIR" "$VERSION_FILE"; do
  if [[ ! -e "$required" ]]; then
    echo "FAIL: ${required} not found — run this from a full checkout."
    exit 1
  fi
done

# `<key>=<value>` lines only; everything else in the pin file is prose.
#
# `|| true` is load-bearing under `set -euo pipefail`. Without it, a missing key
# makes grep exit 1, pipefail carries that out of the command substitution, and
# `set -e` kills the script at the assignment below — before the loop that is
# supposed to report the missing key. Measured, by deleting the pin line: exit
# status 1 with a zero-byte log, which in CI is a red job with no reason given
# and the `FAIL: no '<key>=' line` message never printed.
pinned() {
  grep -E "^$1=" "$VERSION_FILE" | head -1 | cut -d= -f2 || true
}

actionlint_version="$(pinned actionlint_version)"
shellcheck_version="$(pinned shellcheck_version)"

for pin in actionlint_version shellcheck_version; do
  if [[ -z "$(pinned "$pin")" ]]; then
    echo "FAIL: no '${pin}=' line in ${VERSION_FILE}."
    echo "This guard compares the installed tools against that file; without it there is"
    echo "nothing to compare and the check would pass on any version."
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Both tools present, and both at the pinned version.
# ---------------------------------------------------------------------------
if ! command -v actionlint >/dev/null 2>&1; then
  echo "FAIL: actionlint not on PATH."
  echo "Install the pinned version ${actionlint_version} — see ${VERSION_FILE}."
  echo "  brew install actionlint   # then check 'actionlint --version'"
  exit 1
fi

# `actionlint --version` prints the bare version on its first line.
actionlint_actual="$(actionlint --version 2>/dev/null | head -1 | tr -d '[:space:]')"
if [[ "$actionlint_actual" != "$actionlint_version" ]]; then
  echo "FAIL: actionlint version mismatch — this guard cannot tell a real finding from a ruleset difference."
  echo "  pinned (${VERSION_FILE}): ${actionlint_version}"
  echo "  on PATH:                  ${actionlint_actual:-unknown}"
  echo ""
  echo "Install ${actionlint_version}, or — if the upgrade is intentional — bump ${VERSION_FILE}"
  echo "(version AND sha256) and fix whatever the new ruleset finds in the same commit."
  exit 1
fi

# Required, not optional: actionlint silently checks no shell at all when this
# is missing. See the header.
if ! command -v shellcheck >/dev/null 2>&1; then
  echo "FAIL: shellcheck not on PATH."
  echo "actionlint delegates every 'run:' block to shellcheck and does not warn when it"
  echo "is absent — it exits 0 having checked no shell. Running this guard without it"
  echo "would report a pass it did not earn."
  echo "Install the pinned version ${shellcheck_version} — see ${VERSION_FILE}."
  exit 1
fi

# `shellcheck --version` prints a 'version: 0.11.0' line.
shellcheck_actual="$(shellcheck --version 2>/dev/null | grep -E '^version:' | head -1 | awk '{print $2}')"
if [[ "$shellcheck_actual" != "$shellcheck_version" ]]; then
  echo "FAIL: shellcheck version mismatch — this guard cannot tell a real finding from a ruleset difference."
  echo "  pinned (${VERSION_FILE}): ${shellcheck_version}"
  echo "  on PATH:                  ${shellcheck_actual:-unknown}"
  echo ""
  echo "Install ${shellcheck_version}, or — if the upgrade is intentional — bump ${VERSION_FILE}"
  echo "(version AND sha256) and fix whatever the new ruleset finds in the same commit."
  exit 1
fi

# ---------------------------------------------------------------------------
# Partition the workflows. Discovered, not listed, so a new workflow is covered
# the moment it is committed.
# ---------------------------------------------------------------------------
all_workflows=()
while IFS= read -r found; do
  all_workflows+=("$found")
done < <(
  find "$WORKFLOW_DIR" -maxdepth 1 -type f \( -name '*.yml' -o -name '*.yaml' \) \
    | LC_ALL=C sort
)

if [[ ${#all_workflows[@]} -eq 0 ]]; then
  echo "FAIL: found no workflow files under ${WORKFLOW_DIR}."
  echo "Passing by linting nothing is the one outcome this guard must never produce."
  exit 1
fi

is_generated() {
  local candidate="$1" known
  for known in "${GENERATED_WORKFLOWS[@]}"; do
    [[ "$candidate" == "$known" ]] && return 0
  done
  return 1
}

# Every file claimed as generated must exist and still say so itself.
for generated in "${GENERATED_WORKFLOWS[@]}"; do
  if [[ ! -f "$generated" ]]; then
    echo "FAIL: ${generated} is listed here as generated but does not exist."
    echo "Remove the entry from GENERATED_WORKFLOWS in this script — a stale entry is an"
    echo "exclusion nobody is looking at."
    exit 1
  fi
  if ! head -5 "$generated" | grep -qF "$GENERATED_MARKER"; then
    echo "FAIL: ${generated} no longer carries its generator's marker (\"${GENERATED_MARKER}\")."
    echo "Its shellcheck findings are ignored ONLY because it is machine-generated and"
    echo "would be rewritten by the next regeneration. If it is now hand-maintained, that"
    echo "reason is gone: remove it from GENERATED_WORKFLOWS and fix what actionlint says."
    exit 1
  fi
done

hand_written=()
for workflow in "${all_workflows[@]}"; do
  is_generated "$workflow" || hand_written+=("$workflow")
done

if [[ ${#hand_written[@]} -eq 0 ]]; then
  echo "FAIL: every workflow under ${WORKFLOW_DIR} is on the generated list."
  echo "That would leave shellcheck findings ignored everywhere, which is the severity"
  echo "threshold this guard deliberately does not have."
  exit 1
fi

# pyflakes is the other external integration, and it is disabled below for the
# same silent-downgrade reason shellcheck is required: nothing here runs python,
# so leaving it enabled would make the verdict depend on whether the machine
# happens to have pyflakes. If a workflow starts using a python shell, that
# reasoning expires.
python_shells="$(grep -nE '^[[:space:]]*shell:[[:space:]]*python' "${all_workflows[@]}" || true)"
if [[ -n "$python_shells" ]]; then
  echo "FAIL: a workflow declares a python shell, but this guard disables actionlint's"
  echo "pyflakes integration, so that script is checked by nothing:"
  echo "$python_shells"
  echo ""
  echo "Drop '-pyflakes=' below and pin pyflakes in ${VERSION_FILE} alongside the others."
  exit 1
fi

# ---------------------------------------------------------------------------
# Lint. Two invocations, because the flags differ — and they differ in exactly
# one flag, which is easier to audit than a shared config file would be.
# ---------------------------------------------------------------------------
run_actionlint() {
  local label="$1"
  shift
  local rc=0
  actionlint -oneline -no-color -pyflakes= "$@" || rc=$?

  # actionlint exits 1 for findings and >1 for its own failure (bad flags, an
  # unreadable file). Those must not be reported as the same thing: a tool that
  # could not run has not found the workflows to be valid.
  if [[ "$rc" -gt 1 ]]; then
    echo ""
    echo "FAIL: actionlint itself failed with exit status ${rc} on the ${label} workflows."
    echo "That is not a clean result — nothing was validated. Fix the invocation."
    exit 1
  fi
  return "$rc"
}

status=0

echo "actionlint ${actionlint_version} + shellcheck ${shellcheck_version}"
echo ""
echo "Hand-written workflows (all findings enforced):"
printf '  %s\n' "${hand_written[@]}"
if ! run_actionlint "hand-written" "${hand_written[@]}"; then
  status=1
fi

echo ""
echo "Generated workflows (shellcheck findings ignored, everything else enforced):"
printf '  %s\n' "${GENERATED_WORKFLOWS[@]}"
if ! run_actionlint "generated" -ignore "$SHELLCHECK_FINDING" "${GENERATED_WORKFLOWS[@]}"; then
  status=1
fi

if [[ "$status" -ne 0 ]]; then
  echo ""
  echo "FAIL: actionlint reported problems in the workflows above."
  echo ""
  echo "Fix them rather than filtering them. A workflow GitHub rejects at parse time runs"
  echo "zero jobs, which means every check inside it is absent rather than failing — and"
  echo "it is reported against whichever pull request happened to trigger it."
  echo ""
  echo "Reproduce locally with:"
  echo "  bash scripts/check-workflows-are-valid.sh"
  exit 1
fi

echo ""
echo "PASS: ${#all_workflows[@]} workflow file(s) validated — ${#hand_written[@]} hand-written with shell checking enforced, ${#GENERATED_WORKFLOWS[@]} generated with only its generator's shellcheck findings ignored."
exit 0
