#!/usr/bin/env bash
#
# check-failure-diagnostics-are-reachable.sh
#
# HORO-1479. Under `set -e`, a plain assignment from a command substitution
# aborts the script when the substituted command fails. If a pipeline is
# substituted and `pipefail` is also set, it aborts when ANY stage fails —
# including a `grep` that legitimately matched nothing.
#
# So this, which appears correct and is the shape this repository kept
# reaching for:
#
#     version="$(grep -E '^version=' "$FILE" | head -1 | cut -d= -f2)"
#     if [[ -z "$version" ]]; then
#       echo "FAIL: no 'version=' line in ${FILE}."
#       exit 1
#     fi
#
# cannot ever print that message. A missing pin makes the assignment non-zero,
# `set -e` ends the script on that line, and the check written to report
# exactly that condition is dead code. What a reader gets is a red step and an
# empty log — strictly less information than no check at all, because the check
# reads like the case is handled.
#
# WHY A BESPOKE GUARD AND NOT SHELLCHECK
# --------------------------------------
# Because shellcheck does not report this, and this repository already proved
# that the expensive way. `check-shell-scripts-are-clean.sh` runs a pinned copy
# of it over `scripts/*.sh`, and `check-workflows-are-valid.sh` treats its
# absence from actionlint's PATH as a hard failure so every `run:` block is
# checked too. Both bodies of shell are linted. Instances of this defect lived
# in the linted set anyway, and were found by reading rather than by any tool.
#
# (Those two sentences avoid opening a comment line with the tool's name on
# purpose: shellcheck reads `# shellcheck ...` at the start of a line as a
# directive and fails with SC1072/SC1073 when the rest is prose.)
#
# Measured on the pre-fix form of one of them: shellcheck at default severity
# exits 0 with no findings, and with EVERY optional check enabled — including
# `check-extra-masked-returns`, which sounds like it would be the one — reports
# only SC2250, a style note about brace syntax. Nothing in shellcheck knows
# that the `-z` check below it is unreachable.
#
# THE RULE, AND WHY IT IS UNIFORM
# -------------------------------
# If a variable is tested for emptiness or length anywhere in the same shell
# body, its assignment from a command substitution must be failure-tolerant:
# `|| true` or `|| :`, anywhere inside the substitution.
#
# No exceptions, and deliberately no attempt to decide which commands "can
# fail". That judgement is where this defect keeps coming from. `find -print
# -quit` exits 0 when it matches nothing, so its check is genuinely reachable
# today; `awk` over a file that exists always exits 0, so that one is too. Both
# were correct by accident of the tool chosen, not by anything a reader of the
# assignment could see, and both stop being correct the moment someone inserts
# a pipe or swaps the tool. A guard that hard-codes the current answer would
# pass those sites forever while the reasoning that justified them silently
# expired.
#
# So sites like that gain a `|| true` they do not strictly need. It changes no
# behaviour — the substitution already exited 0 — and it makes the claim
# explicit at the point a reader is deciding whether the check below is live.
#
# What the rule does NOT flag is an assignment with no emptiness check below
# it. `REPO_ROOT="$(cd "$(dirname ...)" && pwd)"` should abort if it fails, and
# nothing near it pretends otherwise. The defect is the CONTRADICTION between
# an assignment that aborts and a check that claims to handle the abort, and
# that contradiction is mechanically visible, which is what makes this
# checkable at all.
#
# WHAT IS SCANNED
# ---------------
# Both bodies of shell, because the defect appeared in both:
#   * every `scripts/*.sh`
#   * every `run:` block of every hand-written workflow in `.github/workflows`
#
# `release.yml` is generated by cargo-dist and carries its generator's marker,
# so it is skipped for the same reason `check-workflows-are-valid.sh` ignores
# its shellcheck findings: `dist init` rewrites the file wholesale, so a fix
# here would be reverted by the next regeneration. Stated rather than left
# implied: a regeneration could introduce this defect there and this guard
# would not catch it.
#
# WHO TURNS ERREXIT ON (HORO-1539)
# --------------------------------
# The defect needs errexit in effect, and the two bodies scanned differ in who
# supplies it.
#
# A `scripts/*.sh` file's errexit status is its own business, so it has to say
# so: without the line, the assignment fails, execution carries on, and the
# check below it runs and reports. Nothing is wrong there.
#
# A workflow `run:` block's errexit status belongs to the runner, and GitHub
# invokes a step's default shell as `bash -e {0}` on Linux and macOS. So a
# `run:` block with no errexit line of its own is EXACTLY as vulnerable as one
# with it. This guard used to return 0 on such a block without looking, which
# left one `ci.yml` block silently unanalysed on a rule GitHub does not impose.
# Measured when HORO-1539 was filed: forcing every block to be analysed still
# reported a pass, so nothing in the repository was broken by it. The defect was
# that the guard would not have said so if something were.
#
# Blocks are therefore analysed as errexit-on, EXCEPT where the step's own
# `shell:` key says otherwise — which is read rather than assumed, because
# `shell: bash {0}` genuinely does run with errexit off, and `shell: python` is
# not shell at all and would only manufacture findings if this guard's bash
# patterns were pointed at it.
#
# KNOWN LIMIT
# -----------
# A substitution's extent is found by counting parentheses, so a `(` or `)`
# inside a string or regex is counted too. Every construct in this repository
# balances them, and an imbalance would over-read and therefore over-accept a
# `|| true` from further down — a false PASS, not a false FAIL. That is the
# safer direction for a guard nobody watches, but it is a limit, not a proof.
#
# Exit 0 = pass. Exit 1 = findings, or nothing scanned.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

WORKFLOW_DIR=".github/workflows"
SCRIPT_DIR="scripts"

# Returns 0 and records the site if it has not been reported yet.
#
# `reported` is a local of whichever `assess` call is running, not a global, so
# two assessments in one process cannot see each other's sites.
claim_site() {
  case "$reported" in
    *" $1 "*) return 1 ;;
  esac
  reported="${reported}$1 "
  return 0
}

# Print the body of shell function $2 as defined in file $1, or nothing if it
# is not defined there. Needed because the tolerance can live one level down:
# HORO-1473's own fix put the `|| true` inside a `pinned()` helper, so the call
# site reads `v="$(pinned key)"` with no tolerance visible on it at all — and a
# guard that only looks at the call site reports that fix as the defect.
function_body() {
  awk -v want="$2" '
    !inside {
      if ($0 ~ "^[[:space:]]*(function[[:space:]]+)?" want "[[:space:]]*\\([[:space:]]*\\)") {
        inside = 1
        depth = 0
      } else { next }
    }
    inside {
      n = length($0)
      for (k = 1; k <= n; k++) {
        c = substr($0, k, 1)
        if (c == "{") { depth++; seen = 1 }
        else if (c == "}") depth--
      }
      print
      if (seen && depth <= 0) exit
    }
  ' "$1"
}

# Print the full text of the command substitution that starts on line $2 of
# file $1, however many lines it spans. Depth is tracked from the first `$(`.
substitution_text() {
  awk -v start="$2" '
    NR < start { next }
    {
      line = $0
      if (NR == start) {
        i = index(line, "$(")
        if (i == 0) { print line; exit }
        depth = 0
        rest = substr(line, i)
      } else {
        rest = line
      }
      n = length(rest)
      for (k = 1; k <= n; k++) {
        c = substr(rest, k, 1)
        if (c == "(") depth++
        else if (c == ")") depth--
      }
      print line
      if (depth <= 0) exit
    }
  ' "$1"
}

# The errexit mode for a workflow `run:` block whose step declared `shell: $1`,
# with $1 empty when it declared none. Echoes `assume`, `require` or `skip`.
#
# Ends in `return 0` on purpose, and not only because it always succeeds: the
# `case` patterns below contain a bare `|`, which this guard's own second trigger
# reads as a pipeline that could fail, and a trailing `return 0` is how the rest
# of this repository states that a function's status is its own.
shell_mode() {
  local declared="$1"
  case "$declared" in
    "" | bash | sh)
      # GitHub's default for a `run:` step on Linux and macOS is `bash -e {0}`;
      # `shell: bash` is `bash --noprofile --norc -eo pipefail {0}` and
      # `shell: sh` is `sh -e {0}`. All three carry errexit without the body
      # mentioning it.
      echo assume
      ;;
    python | python3 | pwsh | powershell | cmd | node)
      # Not shell at all. Pointing bash patterns at one of these is how widening
      # a rule invents findings instead of finding them.
      echo skip
      ;;
    *)
      # A custom command template, so read it. `bash {0}` really does run with
      # errexit off, which is the one case the old blanket rule got right.
      if [[ "$declared" == *"-o errexit"* ]] \
        || [[ "$declared" =~ (^|[[:space:]])-[A-Za-z]*e[A-Za-z]*([[:space:]]|$) ]]; then
        echo assume
      else
        echo require
      fi
      ;;
  esac
  return 0
}

# Analyse one shell body. $1 = file of shell source, $2 = label for reporting,
# $3 = line number in the original file that this body starts at (1 for a
# whole script), $4 = `require` if errexit has to be visible in the body for the
# defect to exist, `assume` if whoever runs this body enables it for them.
analyse() {
  local body="$1" label="$2" offset="$3" errexit="${4:-require}"

  # `set -e` has to be in effect for the abort to happen at all.
  #
  # Whether the body has to say so itself is the caller's to answer, because it
  # depends on who runs the body. A standalone script's errexit status is its own
  # business, so `require` is right for one of those: without the line the
  # assignment fails, the script carries on, the check below it runs and reports,
  # and that is not a bug.
  if [[ "$errexit" == "require" ]] \
    && ! grep -qE '^[[:space:]]*set[[:space:]]+-[a-z]*e' "$body"; then
    return 0
  fi

  # Collect every variable tested for emptiness or length, anywhere in the body.
  # Position is not checked: a test placed BEFORE the assignment would be a
  # different bug, there are none, and treating the body as a set keeps this
  # readable.
  #
  # `|| true` on each grep: matching nothing is the common case and, under this
  # script's own `set -euo pipefail`, would otherwise abort right here. This
  # file must not contain the defect it reports.
  # The `-z` pattern requires no opening bracket before it, because a second
  # test joined with `&&` has none: `[[ -z "$a" && -z "$b" ]]` was reporting
  # only `a`, which silently halved the coverage of the one file that uses that
  # shape.
  local checked
  checked="$(
    {
      grep -ohE '(^|[^-[:alnum:]_])-z[[:space:]]+"?\$\{?[A-Za-z_][A-Za-z0-9_]*' "$body" || true
      grep -ohE '\$\{#[A-Za-z_][A-Za-z0-9_]*\}' "$body" || true
    } | grep -oE '[A-Za-z_][A-Za-z0-9_]*\}?$' | tr -d '}' | sort -u || true
  )"

  local name hits hit lineno text full
  while IFS= read -r name; do
    [[ -z "$name" ]] && continue

    # Only a PLAIN assignment. `local x=$(...)`, `readonly`, `export` and
    # `declare` all take the wrapping builtin's own status, which is 0, so
    # `set -e` never fires on them and the check below stays reachable.
    hits="$(grep -nE "^[[:space:]]*${name}=[\"']?\\\$\\(" "$body" || true)"
    [[ -z "$hits" ]] && continue

    while IFS= read -r hit; do
      [[ -z "$hit" ]] && continue
      lineno="${hit%%:*}"
      text="${hit#*:}"

      # The whole substitution, not just its first line. A continuation line
      # carrying the `|| true` is the single most common shape in this
      # repository, and a line-local check reports every one of them as a
      # defect.
      full="$(substitution_text "$body" "$lineno")"
      if [[ "$full" == *'|| true'* || "$full" == *'|| :'* ]]; then
        continue
      fi

      # Tolerance one level down. If the substitution is a call to a function
      # defined in this same body, that function's own `|| true` is what makes
      # the assignment exit 0, and the check below it is reachable.
      local callee callee_body
      callee="$(sed -E 's/^[^(]*\$\([[:space:]]*//; s/[[:space:]].*$//; s/[)"].*$//' <<< "$full")"
      if [[ -n "$callee" && "$callee" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
        callee_body="$(function_body "$body" "$callee")"
        if [[ -n "$callee_body" ]] \
          && { [[ "$callee_body" == *'|| true'* ]] || [[ "$callee_body" == *'|| :'* ]]; }; then
          continue
        fi
      fi

      claim_site "${label}:$((offset + lineno - 1))" || continue
      findings=$((findings + 1))
      echo ""
      echo "  ${label}:$((offset + lineno - 1))"
      echo "    ${text#"${text%%[![:space:]]*}"}"
      echo "    \$${name} is tested for emptiness or length in this shell body, but"
      echo "    nothing in this substitution tolerates failure, so under 'set -e' the"
      echo "    body ends here and that test cannot run in the case it was written for."
    done <<< "$hits"
  done <<< "$checked"

  # --- second trigger: calling a helper that can report absence -------------
  #
  # The rule above keys on a variable tested by name, and that is not how every
  # instance of this defect is written. `check-workflows-are-valid.sh` assigns
  # two pins and then reports a missing one from a loop that re-invokes the
  # helper, so neither variable is ever `-z`-tested — the first trigger sees
  # nothing there even though it is the same bug in the same shape. That is the
  # HORO-1473 regression this guard most needs to catch, so the first trigger
  # alone is not enough.
  #
  # What links them is the helper. A function that pulls a value out of a file,
  # or looks for a process, reports absence — by printing nothing, or by
  # returning non-zero on purpose. Either way absence is part of its contract,
  # not a malfunction. Assigning its output with a plain assignment and no `||`
  # handler converts that contract into "end the script here", and whatever was
  # written to report the absence does not run.
  #
  # Reported at the CALL SITE rather than at the helper, because that is where
  # the fix belongs. A helper carrying a deliberate `return 1` cannot be fixed
  # by making its own pipeline tolerant — `survivor_bundle` in
  # `check-single-instance-lifecycle.sh` is exactly that shape — so the handler
  # has to go on the assignment.
  local fn fname fline fn_body
  while IFS= read -r fn; do
    [[ -z "$fn" ]] && continue
    fline="${fn%%:*}"
    fname="$(sed -E 's/^[0-9]+:[[:space:]]*(function[[:space:]]+)?([A-Za-z_][A-Za-z0-9_]*).*/\2/' <<< "$fn" || true)"
    [[ -z "$fname" ]] && continue

    fn_body="$(function_body "$body" "$fname")"

    # Can it report absence by exiting non-zero?
    #
    # A trailing `return 0` settles it: the function's status is 0 whatever its
    # last pipeline did. `check-single-instance-lifecycle.sh` uses that
    # deliberately — `all_instances`, `other_builds` and `rig_pids` each end with
    # one, and the comment above the first says exactly why ("finding nothing is
    # a normal answer and `set -o pipefail` would otherwise carry a falsy last
    # test out of here as a failure"). Treating that as unprotected reported the
    # file that already got this right, which is the opposite of useful.
    local can_fail=0 reason=""
    local ends_return_zero=0
    # Not anchored to the start of a line: a one-line helper puts it inline, as
    # `rig_count() { rig_pids | wc -l | tr -d ' '; return 0; }` does.
    if grep -vE '^[[:space:]]*(#|$)' <<< "$fn_body" | tail -n 2 \
      | grep -qE '(^|[^[:alnum:]_])return[[:space:]]+0([^0-9]|$)'; then
      ends_return_zero=1
    fi

    # A pipeline means a `|` that is not part of `||`. Matching a bare `|`
    # counted every `|| echo` fallback as a pipeline, which flagged
    # `identifier_of` — a function whose whole body is that fallback.
    if [[ "$ends_return_zero" -eq 0 ]] \
      && grep -qE '([^|]\|[^|]|^\|[^|])' <<< "$fn_body" \
      && [[ "$fn_body" != *'|| true'* ]] && [[ "$fn_body" != *'|| :'* ]]; then
      can_fail=1
      reason="its pipeline has no '|| true' and it does not end in 'return 0', so a stage matching nothing fails it"
    fi
    # Any `return <non-zero>`, wherever it sits on the line. Anchoring this to
    # the start of a line missed `bundle=$(survivor_bundle) || return 1`, which
    # is how `survivor_version` signals absence — so both its unprotected
    # callers went unreported. Comment lines are stripped first so prose about
    # returning 1 does not count.
    if grep -vE '^[[:space:]]*#' <<< "$fn_body" \
      | grep -qE '(^|[^[:alnum:]_])return[[:space:]]+[1-9]'; then
      can_fail=1
      reason="it returns non-zero on purpose to report absence"
    fi
    [[ "$can_fail" -eq 0 ]] && continue

    local cline cno cfull
    while IFS= read -r cline; do
      [[ -z "$cline" ]] && continue
      cno="${cline%%:*}"
      cfull="$(substitution_text "$body" "$cno")"

      # Any `||` handler means the status is handled — `|| true`, `|| return 1`
      # and `|| fail "..."` are all fine, and the last two are how this
      # repository already handles it in the places it got right.
      if [[ "$cfull" == *'||'* ]]; then
        continue
      fi

      claim_site "${label}:$((offset + cno - 1))" || continue
      findings=$((findings + 1))
      echo ""
      echo "  ${label}:$((offset + cno - 1))"
      echo "    ${cline#*:}"
      echo "    ${fname}() (defined at line $((offset + fline - 1))) can exit non-zero:"
      echo "    ${reason}. This assignment has no '||' handler, so under 'set -e' the"
      echo "    body ends here and whatever reports the absence below does not run."
    done <<< "$(grep -nE "^[[:space:]]*[A-Za-z_][A-Za-z0-9_]*=[\"']?\\\$\\([[:space:]]*${fname}([[:space:]\")]|$)" "$body" || true)"
  done <<< "$(grep -nE '^[[:space:]]*(function[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*[[:space:]]*\([[:space:]]*\)[[:space:]]*\{' "$body" || true)"
}

# --- one assessment ---------------------------------------------------------
#
# Everything below runs against the checkout at $1, in a subshell, so that the
# self-test can drive the real rules over fixtures rather than over a second
# copy of them. A guard whose self-test exercises a paraphrase of its rules
# proves nothing about the rules.
#
# Returns 0 when every emptiness or length check in that checkout is reachable.
assess() (
  local root="$1"
  cd "$root" || {
    echo "FAIL: ${root} is not a directory that can be entered."
    return 1
  }

  local WORK
  WORK="$(mktemp -d)"
  # shellcheck disable=SC2064  # $WORK must expand now, not at trap time.
  trap "rm -rf '$WORK'" EXIT

  local findings=0
  local blocks_scanned=0
  local files_scanned=0

  # Sites already printed, as "label:line". The two triggers in `analyse`
  # overlap — a helper call whose variable is also `-z`-tested satisfies both —
  # and reporting one site twice would inflate the count a reader uses to judge
  # progress.
  local reported=" "

  # --- scripts --------------------------------------------------------------

  local f
  shopt -s nullglob
  for f in "$SCRIPT_DIR"/*.sh; do
    files_scanned=$((files_scanned + 1))
    analyse "$f" "$f" 1 require
  done
  shopt -u nullglob

  # --- workflow run: blocks -------------------------------------------------

  local wf blockfile startline blockshell mode
  local blocks_skipped=0
  for wf in "$WORKFLOW_DIR"/*.yml "$WORKFLOW_DIR"/*.yaml; do
    [[ -f "$wf" ]] || continue

    # Skip generated files, as documented in the header.
    #
    # Anchored to the banner a generator writes at the top, not searched
    # file-wide: `ci.yml` has a comment about release.yml *being* generated, and
    # matching that excluded 567 hand-written lines and seven `run:` blocks from
    # this guard while it reported a pass. A generated file announces itself on
    # its first line; a file merely discussing one does not.
    #
    # One awk rather than `head -5 | grep -q`, because that pipeline's status is
    # not reliably grep's under this script's own `set -o pipefail`: `grep -q`
    # leaves on the first match, which here is line 1, and a SIGPIPE'd `head`
    # would be the rightmost non-zero status — turning a matched banner into
    # "not generated". It holds today only because `head` writes all five lines
    # before `grep` goes.
    #
    # `exit` with no status, and the verdict taken in END, because awk runs END
    # on its way out of an `exit` in a rule: an `exit 0` there is overridden by
    # whatever END exits with. Measured on that form — release.yml was scanned
    # anyway, 29 `run:` blocks instead of 18.
    if awk 'NR > 5 { exit }
            tolower($0) ~ /(generated by|autogenerated|do not edit).*(dist|cargo-dist)/ { found = 1; exit }
            END { exit !found }' "$wf"; then
      echo "note: skipping ${wf} — generated; its generator owns its shell."
      continue
    fi

    files_scanned=$((files_scanned + 1))

    # Extract each `run:` block scalar. A block scalar's body is every following
    # line indented deeper than the key, plus blank lines. Written as awk rather
    # than a YAML parser so this guard needs nothing installed — the same reason
    # every other check in this directory is shell.
    #
    # Emits one file per block, plus an index of
    # "file<TAB>first-body-line<TAB>declared shell".
    #
    # The third field is why this is no longer a two-rule awk: the `shell:` key
    # that governs a block is a sibling of its `run:` key and may sit on either
    # side of it, so a block's entry cannot be written until its step ends. Keys
    # of one step share a column, which is the column of `run:` itself and not
    # the line's indentation — the first key of a step carries the list dash.
    awk -v outdir="$WORK" '
      function indent_of(s) { match(s, /^[ ]*/); return RLENGTH }
      function keycol(s) {
        if (match(s, /^[ ]*-[ ]+/)) return RLENGTH
        return indent_of(s)
      }
      function shellval(s,   v, q) {
        v = s
        sub(/^[ ]*(-[ ]+)?shell:[ ]*/, "", v)
        sub(/[ ]+#.*$/, "", v)
        q = sprintf("%c%c", 34, 39)
        gsub("^[" q "]+|[" q "]+$", "", v)
        sub(/[ ]+$/, "", v)
        return v
      }
      function flush() {
        if (curblock != "") {
          print curblock "\t" curstart "\t" curshell > (outdir "/index")
          curblock = ""
        }
      }
      BEGIN { pendcol = -1; stepcol = -1 }
      {
        if (inblock) {
          if ($0 ~ /^[ ]*$/) { print "" > out; next }
          ci = indent_of($0)
          if (blockind < 0) { blockind = ci }
          if (ci >= blockind) { print substr($0, blockind + 1) > out; next }
          inblock = 0
          close(out)
        }

        if ($0 ~ /^[ ]*$/) next

        kc = keycol($0)
        isitem = ($0 ~ /^[ ]*-[ ]/)

        # A shallower key, or a new list item at the same column, ends the step
        # the pending block belongs to, so its shell can no longer change.
        if (curblock != "" && (kc < stepcol || (isitem && kc <= stepcol))) flush()

        if (isitem || (pendcol >= 0 && kc < pendcol)) { pendshell = ""; pendcol = -1 }

        if ($0 ~ /^[ ]*(-[ ]+)?shell:/) {
          if (curblock != "" && kc == stepcol) { curshell = shellval($0) }
          else { pendshell = shellval($0); pendcol = kc }
          next
        }

        if ($0 ~ /^[ ]*(-[ ]+)?run:[ ]*[|>]/) {
          flush()
          n++
          out = outdir "/block-" n ".sh"
          curblock = out
          curstart = NR + 1
          stepcol = kc
          curshell = (pendcol == kc) ? pendshell : ""
          pendshell = ""
          pendcol = -1
          inblock = 1
          blockind = -1
          next
        }
      }
      END { if (inblock) close(out); flush() }
    ' "$wf"

    if [[ -f "$WORK/index" ]]; then
      while IFS=$'\t' read -r blockfile startline blockshell; do
        [[ -f "$blockfile" ]] || continue
        mode="$(shell_mode "$blockshell")"
        if [[ "$mode" == "skip" ]]; then
          blocks_skipped=$((blocks_skipped + 1))
          echo "note: skipping the run: block at ${wf}:${startline} —" \
            "shell: ${blockshell} is not shell, so a shell rule has nothing to say about it."
          continue
        fi
        blocks_scanned=$((blocks_scanned + 1))
        analyse "$blockfile" "$wf" "$startline" "$mode"
      done < "$WORK/index"
      rm -f "$WORK/index" "$WORK"/block-*.sh
    fi
  done

  # --- anti-vacuity ---------------------------------------------------------
  #
  # Zero findings over zero input is the exact reading this guard exists to
  # prevent elsewhere, so it must not produce it itself.

  if [[ "$files_scanned" -eq 0 ]]; then
    echo "FAIL: scanned no files at all. Run this from a full checkout."
    return 1
  fi

  if [[ "$blocks_scanned" -eq 0 ]]; then
    echo "FAIL: extracted no 'run:' blocks from ${WORKFLOW_DIR}."
    echo "Either the workflows have none, or the extraction is broken. Both are"
    echo "reasons to refuse rather than report clean."
    return 1
  fi

  if [[ "$findings" -eq 0 ]]; then
    echo "PASS: every emptiness or length check is reachable."
    echo "  ${files_scanned} file(s), ${blocks_scanned} workflow run: block(s) scanned."
    return 0
  fi

  echo ""
  echo "FAIL: ${findings} failure diagnostic(s) that cannot run in the case they report."
  echo ""
  echo "Each site above pairs an assignment that aborts the script with a check"
  echo "that claims to handle the abort. The check is dead code, and the failure it"
  echo "was written for shows up as a red step with an empty log — less information"
  echo "than no check at all, because the check reads like the case is covered."
  echo ""
  echo "Fix by making the assignment tolerant so the check can run:"
  echo "    value=\"\$(grep -E \"^\$1=\" \"\$FILE\" | head -1 | cut -d= -f2 || true)\""
  echo "then leave the existing emptiness check exactly as it is."
  echo ""
  echo "Do not instead delete the check. The check is the useful half; the"
  echo "assignment is what was wrong."
  return 1
)

# --- entry point ------------------------------------------------------------

assess "$REPO_ROOT"
