//! What Docker itself can state about one of its own objects (HORO-1544).
//!
//! # Why this is a separate vocabulary
//!
//! Before this ticket everything Docker owned arrived as one of two
//! resource kinds and carried no lifecycle information at all, so the only
//! way to stay safe was to refuse the whole category: `protected.rs`
//! classified every `DockerImageCache` resource `Protected` with reason
//! `protected_persistent_volume`, on the stated grounds that a detector
//! "cannot distinguish a persistent Docker volume from disposable image
//! cache". That refusal was correct and it was also the reason the product
//! could say nothing useful about 21 GB of a developer's disk.
//!
//! An image, a container and a volume are not three sizes of the same
//! thing. A container has a writable layer that exists nowhere else; a
//! named volume is where a developer's local Postgres keeps its data; an
//! image usually came from a registry and sometimes was built here and
//! exists nowhere else. The distinctions that matter are not "how big" but
//! *is anything using it*, *whose data is it*, and *what else points at
//! it* — so those are the three fields, and each one has an explicit
//! `Unknown` rather than a default that reads as permission.
//!
//! # These are observations, not verdicts
//!
//! Nothing here says AUTO_SAFE, ASK or PROTECTED. [`DockerActivity`] says
//! whether Docker reported the object as in use, not whether it may be
//! deleted; `docker system df` cheerfully reports 11.66 GB of images as
//! "Reclaimable (100%)" while six containers are running, and "Docker
//! offered to reclaim it" is not authority to reclaim it. The policy layer
//! reads these values; it does not take instructions from them.

use super::model::ResourceId;
use super::probe::ProbeOutcome;

/// Whether anything is using this Docker object right now.
///
/// `Unknown` is not a quieter `Inactive`. A running container is
/// active-use evidence and an image a running container needs is active-use
/// evidence too, so the difference between "Docker said nothing holds this"
/// and "Docker was not asked, or could not answer" decides whether the
/// object reaches the policy layer with an active-use reason attached.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DockerActivity {
    /// Docker reported this object as in use: a running container, or an
    /// object a running container depends on.
    Active,
    /// Docker reported this object as not in use. A real answer, and still
    /// not deletion authority — a stopped container is inactive and holds
    /// its writable layer regardless.
    Inactive,
    /// Docker did not answer, was not asked, or gave an answer this code
    /// declined to interpret.
    Unknown,
}

impl DockerActivity {
    /// Stable snake_case token, for reports and for the model projection.
    pub fn tag(self) -> &'static str {
        match self {
            Self::Active => "active",
            Self::Inactive => "inactive",
            Self::Unknown => "unknown",
        }
    }

    /// Every variant, in declaration order. Lets a test cover the enum
    /// without being edited when a variant is added.
    pub const ALL: [DockerActivity; 3] = [Self::Active, Self::Inactive, Self::Unknown];
}

/// Whose data this object holds, as far as Docker can state it.
///
/// The campaign's Maven argument applies to Docker too: a directory's
/// category is not readable from its name. A named volume was created by a
/// human or a compose file that chose the name, and its contents may be the
/// only copy of a local database; an anonymous volume was minted by the
/// daemon to satisfy a `VOLUME` instruction. Docker can state which of
/// those happened, so that is what this records — and where it cannot, the
/// answer is `Unknown` and the fail-closed path is taken.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DockerPersistence {
    /// Named, declared, or otherwise created deliberately. Treated as
    /// possibly holding the only copy of the user's data.
    UserManaged,
    /// Created by Docker for its own purposes and regenerated by rerunning
    /// the work that produced it — build cache being the clearest case.
    ToolManaged,
    /// Docker did not state which, so neither does this.
    Unknown,
}

impl DockerPersistence {
    /// Stable snake_case token, for reports and for the model projection.
    pub fn tag(self) -> &'static str {
        match self {
            Self::UserManaged => "user_managed",
            Self::ToolManaged => "tool_managed",
            Self::Unknown => "unknown",
        }
    }

    /// Every variant, in declaration order.
    pub const ALL: [DockerPersistence; 3] = [Self::UserManaged, Self::ToolManaged, Self::Unknown];
}

/// Which other Docker objects hold a reference to this one.
///
/// An empty `referenced_by` beside an `Observed` outcome means Docker was
/// asked and said nothing references this object. That is the fact
/// `ProbeOutcome::Unavailable` exists to keep separate from "the reference
/// query did not run", which would otherwise read identically.
#[derive(Debug, Clone, PartialEq)]
pub struct DockerReferences {
    /// The referencing objects, as resource identities so the workspace
    /// graph can link an image to the containers that need it rather than
    /// re-deriving the relationship from strings.
    pub referenced_by: Vec<ResourceId>,
    /// How many of those referrers Docker reported as running. A count
    /// rather than a filtered list, because that is all any consumer needs
    /// and a count cannot leak an identity.
    pub active_referrers: u32,
}

impl DockerReferences {
    /// Docker was asked and reported no referrers.
    pub fn none() -> Self {
        Self {
            referenced_by: Vec::new(),
            active_referrers: 0,
        }
    }
}

/// The lifecycle facts one Docker object carries, attached to its
/// [`super::Evidence`].
///
/// Three independent questions, deliberately not collapsed into a single
/// "state" string: an object can be inactive and user-managed (a stopped
/// container holding its writable layer), active and tool-managed (build
/// cache a running build is writing), or unknown on every axis at once.
#[derive(Debug, Clone, PartialEq)]
pub struct DockerLifecycle {
    pub activity: DockerActivity,
    pub persistence: DockerPersistence,
    pub references: ProbeOutcome<DockerReferences>,
}

impl DockerLifecycle {
    /// Every axis unknown and the reference query not attempted — the shape
    /// to use when Docker answered with less than expected, so that no
    /// caller has to invent a value to fill the struct.
    pub fn unknown(reason: super::ProbeReason) -> Self {
        Self {
            activity: DockerActivity::Unknown,
            persistence: DockerPersistence::Unknown,
            references: ProbeOutcome::Unavailable(reason),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evidence::ProbeReason;

    /// The tags stand in for the values in reports and in the model
    /// payload, so two variants sharing one would erase exactly the
    /// distinction the enum exists to carry. Driven from `ALL` so a new
    /// variant is covered unedited.
    #[test]
    fn every_activity_has_a_distinct_non_empty_tag() {
        let mut tags: Vec<&str> = DockerActivity::ALL.iter().map(|a| a.tag()).collect();
        assert_eq!(tags.len(), 3, "ALL must list every variant");
        for tag in &tags {
            assert!(!tag.is_empty());
        }
        tags.sort_unstable();
        tags.dedup();
        assert_eq!(tags.len(), DockerActivity::ALL.len());
    }

    #[test]
    fn every_persistence_has_a_distinct_non_empty_tag() {
        let mut tags: Vec<&str> = DockerPersistence::ALL.iter().map(|p| p.tag()).collect();
        assert_eq!(tags.len(), 3, "ALL must list every variant");
        for tag in &tags {
            assert!(!tag.is_empty());
        }
        tags.sort_unstable();
        tags.dedup();
        assert_eq!(tags.len(), DockerPersistence::ALL.len());
    }

    /// `Inactive` and `Unknown` must not share a token: the whole point of
    /// the third variant is that a model or a reader can tell "Docker says
    /// nothing holds this" from "nobody asked".
    #[test]
    fn unknown_activity_is_not_spelled_like_inactive() {
        assert_ne!(
            DockerActivity::Unknown.tag(),
            DockerActivity::Inactive.tag()
        );
    }

    /// An observed empty reference list is a positive statement; an
    /// unavailable reference query is not. Asserting the two are
    /// distinguishable here pins the property the policy layer relies on.
    #[test]
    fn observed_empty_references_differ_from_an_unavailable_query() {
        let asked = ProbeOutcome::Observed(DockerReferences::none());
        let not_asked: ProbeOutcome<DockerReferences> =
            ProbeOutcome::Unavailable(ProbeReason::NotAttempted);

        assert!(asked.is_observed());
        assert!(!not_asked.is_observed());
        assert_ne!(asked, not_asked);
    }

    #[test]
    fn unknown_lifecycle_carries_the_reason_and_asserts_nothing_else() {
        let lifecycle = DockerLifecycle::unknown(ProbeReason::ToolNotRunning);

        assert_eq!(lifecycle.activity, DockerActivity::Unknown);
        assert_eq!(lifecycle.persistence, DockerPersistence::Unknown);
        assert_eq!(
            lifecycle.references,
            ProbeOutcome::Unavailable(ProbeReason::ToolNotRunning)
        );
    }
}
